/* words.js — 500 high-frequency Thai words for the Thai Vocab 500 game.
 *
 * Ordered by teaching rank: drawn from common Thai frequency lists (Thai National
 * Corpus / core-vocabulary lists) and grouped into thematic runs inside each
 * frequency band so that a unit of 25 words hangs together.
 *
 * Entry shape:
 *   { rank, thai, roman, english, pos, category, art }
 *
 * roman  — RTGS consonants with long vowels doubled, plus tone diacritics:
 *            (none) = mid   à = low   â = falling   á = high   ǎ = rising
 *          The game derives the spoken tone of each syllable from these marks and
 *          shows it in the card tooltip.
 *
 * art    — one of:
 *   { type: "emoji", char: "🐕" }          concrete nouns: one big emoji glyph
 *   { type: "glyph", icon: "person", mod: "arrow-right" }  verbs / abstract words:
 *                                          composed from the inline SVG primitive
 *                                          library in index.html (icon + optional
 *                                          badge) over a category-coloured tile
 *   { type: "text",  gloss: "I / me" }     function words & pronouns: typographic tile
 */

const WORDS = [
  { rank: 1, thai: "ที่", roman: "thîi", english: "at, that, place", pos: "particle", category: "function words", art: {type:"text", gloss:"at / that"} },
  { rank: 2, thai: "เป็น", roman: "pen", english: "to be", pos: "verb", category: "verbs", art: {type:"glyph", icon:"equals"} },
  { rank: 3, thai: "ใน", roman: "nai", english: "in, inside", pos: "prep", category: "function words", art: {type:"text", gloss:"in / inside"} },
  { rank: 4, thai: "มี", roman: "mii", english: "to have", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"plus"} },
  { rank: 5, thai: "ของ", roman: "khǒng", english: "of, belongings", pos: "noun", category: "function words", art: {type:"text", gloss:"of / belonging to"} },
  { rank: 6, thai: "ได้", roman: "dâi", english: "can, to get", pos: "verb", category: "verbs", art: {type:"glyph", icon:"check"} },
  { rank: 7, thai: "ไม่", roman: "mâi", english: "not, no", pos: "adverb", category: "function words", art: {type:"text", gloss:"not / no"} },
  { rank: 8, thai: "ให้", roman: "hâi", english: "to give", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"arrow-right"} },
  { rank: 9, thai: "และ", roman: "láe", english: "and", pos: "conjunction", category: "function words", art: {type:"text", gloss:"and"} },
  { rank: 10, thai: "ว่า", roman: "wâa", english: "to say, that", pos: "verb", category: "verbs", art: {type:"glyph", icon:"speech"} },
  { rank: 11, thai: "จะ", roman: "chà", english: "will (future)", pos: "auxiliary", category: "function words", art: {type:"text", gloss:"will"} },
  { rank: 12, thai: "มา", roman: "maa", english: "to come", pos: "verb", category: "verbs", art: {type:"glyph", icon:"arrow-left"} },
  { rank: 13, thai: "นี้", roman: "níi", english: "this", pos: "determiner", category: "function words", art: {type:"text", gloss:"this"} },
  { rank: 14, thai: "กับ", roman: "kàp", english: "with", pos: "prep", category: "function words", art: {type:"text", gloss:"with"} },
  { rank: 15, thai: "คน", roman: "khon", english: "person", pos: "noun", category: "family & people", art: {type:"emoji", char:"🧑"} },
  { rank: 16, thai: "ทำ", roman: "tham", english: "to do, to make", pos: "verb", category: "verbs", art: {type:"glyph", icon:"tool"} },
  { rank: 17, thai: "ไป", roman: "pai", english: "to go", pos: "verb", category: "verbs", art: {type:"glyph", icon:"arrow-right"} },
  { rank: 18, thai: "อยู่", roman: "yùu", english: "to stay, to be located", pos: "verb", category: "verbs", art: {type:"glyph", icon:"target"} },
  { rank: 19, thai: "แล้ว", roman: "láeo", english: "already", pos: "adverb", category: "function words", art: {type:"text", gloss:"already"} },
  { rank: 20, thai: "เรา", roman: "rao", english: "we, us", pos: "pronoun", category: "pronouns", art: {type:"text", gloss:"we / us"} },
  { rank: 21, thai: "ต้อง", roman: "tông", english: "must, have to", pos: "auxiliary", category: "function words", art: {type:"text", gloss:"must / have to"} },
  { rank: 22, thai: "การ", roman: "kaan", english: "the act of", pos: "noun", category: "function words", art: {type:"text", gloss:"the act of"} },
  { rank: 23, thai: "ความ", roman: "khwaam", english: "-ness, -ity", pos: "noun", category: "function words", art: {type:"text", gloss:"-ness / -ity"} },
  { rank: 24, thai: "ก็", roman: "kô", english: "also, then", pos: "adverb", category: "function words", art: {type:"text", gloss:"also / then"} },
  { rank: 25, thai: "ผู้", roman: "phûu", english: "one who", pos: "noun", category: "family & people", art: {type:"text", gloss:"one who"} },
  { rank: 26, thai: "ใช้", roman: "chái", english: "to use", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"tool"} },
  { rank: 27, thai: "คือ", roman: "khue", english: "to be, namely", pos: "verb", category: "verbs", art: {type:"glyph", icon:"equals", mod:"speech"} },
  { rank: 28, thai: "หรือ", roman: "rǔe", english: "or", pos: "conjunction", category: "function words", art: {type:"text", gloss:"or"} },
  { rank: 29, thai: "แต่", roman: "tàe", english: "but", pos: "conjunction", category: "function words", art: {type:"text", gloss:"but"} },
  { rank: 30, thai: "ถ้า", roman: "thâa", english: "if", pos: "conjunction", category: "function words", art: {type:"text", gloss:"if"} },
  { rank: 31, thai: "เพราะ", roman: "phró", english: "because", pos: "conjunction", category: "function words", art: {type:"text", gloss:"because"} },
  { rank: 32, thai: "เมื่อ", roman: "mûea", english: "when (past)", pos: "conjunction", category: "function words", art: {type:"text", gloss:"when (past)"} },
  { rank: 33, thai: "ดี", roman: "dii", english: "good", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"star"} },
  { rank: 34, thai: "ใหญ่", roman: "yài", english: "big", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"square-big"} },
  { rank: 35, thai: "เล็ก", roman: "lék", english: "small", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"square-small"} },
  { rank: 36, thai: "มาก", roman: "mâak", english: "much, very", pos: "adverb", category: "adjectives", art: {type:"glyph", icon:"bars", mod:"plus"} },
  { rank: 37, thai: "น้อย", roman: "nói", english: "few, little", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"bars", mod:"minus"} },
  { rank: 38, thai: "ใหม่", roman: "mài", english: "new", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"spark"} },
  { rank: 39, thai: "เก่า", roman: "kào", english: "old (things)", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"box", mod:"clock"} },
  { rank: 40, thai: "ดู", roman: "duu", english: "to look, to watch", pos: "verb", category: "verbs", art: {type:"glyph", icon:"eye"} },
  { rank: 41, thai: "เห็น", roman: "hěn", english: "to see", pos: "verb", category: "verbs", art: {type:"glyph", icon:"eye", mod:"check"} },
  { rank: 42, thai: "รู้", roman: "rúu", english: "to know", pos: "verb", category: "verbs", art: {type:"glyph", icon:"brain"} },
  { rank: 43, thai: "คิด", roman: "khít", english: "to think", pos: "verb", category: "verbs", art: {type:"glyph", icon:"thought"} },
  { rank: 44, thai: "พูด", roman: "phûut", english: "to speak", pos: "verb", category: "verbs", art: {type:"glyph", icon:"mouth"} },
  { rank: 45, thai: "บอก", roman: "bòok", english: "to tell", pos: "verb", category: "verbs", art: {type:"glyph", icon:"speech", mod:"arrow-right"} },
  { rank: 46, thai: "ฟัง", roman: "fang", english: "to listen", pos: "verb", category: "verbs", art: {type:"glyph", icon:"ear"} },
  { rank: 47, thai: "อ่าน", roman: "àan", english: "to read", pos: "verb", category: "verbs", art: {type:"glyph", icon:"book"} },
  { rank: 48, thai: "เขียน", roman: "khǐan", english: "to write", pos: "verb", category: "verbs", art: {type:"glyph", icon:"pen"} },
  { rank: 49, thai: "เรียน", roman: "rian", english: "to study", pos: "verb", category: "verbs", art: {type:"glyph", icon:"book", mod:"brain"} },
  { rank: 50, thai: "สอน", roman: "sǒon", english: "to teach", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person", mod:"book"} },
  { rank: 51, thai: "บ้าน", roman: "bâan", english: "house, home", pos: "noun", category: "places", art: {type:"emoji", char:"🏠"} },
  { rank: 52, thai: "เมือง", roman: "mueang", english: "city, town", pos: "noun", category: "places", art: {type:"emoji", char:"🏙️"} },
  { rank: 53, thai: "ประเทศ", roman: "prathêet", english: "country", pos: "noun", category: "places", art: {type:"emoji", char:"🌏"} },
  { rank: 54, thai: "ไทย", roman: "thai", english: "Thai", pos: "adjective", category: "places", art: {type:"emoji", char:"🇹🇭"} },
  { rank: 55, thai: "โรงเรียน", roman: "roongrian", english: "school", pos: "noun", category: "places", art: {type:"emoji", char:"🏫"} },
  { rank: 56, thai: "ตลาด", roman: "talàat", english: "market", pos: "noun", category: "places", art: {type:"emoji", char:"🏪"} },
  { rank: 57, thai: "ร้าน", roman: "ráan", english: "shop", pos: "noun", category: "places", art: {type:"emoji", char:"🏬"} },
  { rank: 58, thai: "ถนน", roman: "thanǒn", english: "road, street", pos: "noun", category: "places", art: {type:"emoji", char:"🛣️"} },
  { rank: 59, thai: "ห้อง", roman: "hông", english: "room", pos: "noun", category: "places", art: {type:"glyph", icon:"house", mod:"grid"} },
  { rank: 60, thai: "โรงพยาบาล", roman: "roongphayaabaan", english: "hospital", pos: "noun", category: "places", art: {type:"emoji", char:"🏥"} },
  { rank: 61, thai: "วัด", roman: "wát", english: "temple", pos: "noun", category: "places", art: {type:"emoji", char:"🛕"} },
  { rank: 62, thai: "สนามบิน", roman: "sanǎambin", english: "airport", pos: "noun", category: "places", art: {type:"emoji", char:"🛫"} },
  { rank: 63, thai: "ธนาคาร", roman: "thanaakhaan", english: "bank", pos: "noun", category: "places", art: {type:"emoji", char:"🏦"} },
  { rank: 64, thai: "โรงแรม", roman: "roongraem", english: "hotel", pos: "noun", category: "places", art: {type:"emoji", char:"🏨"} },
  { rank: 65, thai: "สวน", roman: "sǔan", english: "garden, park", pos: "noun", category: "places", art: {type:"emoji", char:"🪴"} },
  { rank: 66, thai: "ทะเล", roman: "thalee", english: "sea", pos: "noun", category: "nature", art: {type:"emoji", char:"🌊"} },
  { rank: 67, thai: "ภูเขา", roman: "phuukhǎo", english: "mountain", pos: "noun", category: "nature", art: {type:"emoji", char:"⛰️"} },
  { rank: 68, thai: "แม่น้ำ", roman: "mâenáam", english: "river", pos: "noun", category: "nature", art: {type:"emoji", char:"🏞️"} },
  { rank: 69, thai: "ฝน", roman: "fǒn", english: "rain", pos: "noun", category: "nature", art: {type:"emoji", char:"🌧️"} },
  { rank: 70, thai: "ลม", roman: "lom", english: "wind", pos: "noun", category: "nature", art: {type:"emoji", char:"🌬️"} },
  { rank: 71, thai: "ไฟ", roman: "fai", english: "fire", pos: "noun", category: "nature", art: {type:"emoji", char:"🔥"} },
  { rank: 72, thai: "น้ำ", roman: "náam", english: "water", pos: "noun", category: "food & drink", art: {type:"emoji", char:"💧"} },
  { rank: 73, thai: "ต้นไม้", roman: "tônmáai", english: "tree", pos: "noun", category: "nature", art: {type:"emoji", char:"🌳"} },
  { rank: 74, thai: "ดอกไม้", roman: "dòokmáai", english: "flower", pos: "noun", category: "nature", art: {type:"emoji", char:"🌸"} },
  { rank: 75, thai: "ฟ้า", roman: "fáa", english: "sky", pos: "noun", category: "nature", art: {type:"emoji", char:"🌤️"} },
  { rank: 76, thai: "พ่อ", roman: "phôo", english: "father", pos: "noun", category: "family & people", art: {type:"emoji", char:"👨‍👦"} },
  { rank: 77, thai: "แม่", roman: "mâe", english: "mother", pos: "noun", category: "family & people", art: {type:"emoji", char:"👩‍👧"} },
  { rank: 78, thai: "ลูก", roman: "lûuk", english: "child (offspring)", pos: "noun", category: "family & people", art: {type:"emoji", char:"👶"} },
  { rank: 79, thai: "พี่", roman: "phîi", english: "older sibling", pos: "noun", category: "family & people", art: {type:"glyph", icon:"people", mod:"arrow-up"} },
  { rank: 80, thai: "น้อง", roman: "nóng", english: "younger sibling", pos: "noun", category: "family & people", art: {type:"glyph", icon:"people", mod:"arrow-down"} },
  { rank: 81, thai: "เพื่อน", roman: "phûean", english: "friend", pos: "noun", category: "family & people", art: {type:"emoji", char:"🧑‍🤝‍🧑"} },
  { rank: 82, thai: "ครู", roman: "khruu", english: "teacher", pos: "noun", category: "family & people", art: {type:"emoji", char:"👩‍🏫"} },
  { rank: 83, thai: "นักเรียน", roman: "nákrian", english: "student", pos: "noun", category: "family & people", art: {type:"emoji", char:"🧑‍🎓"} },
  { rank: 84, thai: "หมอ", roman: "mǒo", english: "doctor", pos: "noun", category: "family & people", art: {type:"emoji", char:"👨‍⚕️"} },
  { rank: 85, thai: "ตำรวจ", roman: "tamrùat", english: "police officer", pos: "noun", category: "family & people", art: {type:"emoji", char:"👮"} },
  { rank: 86, thai: "ผู้ชาย", roman: "phûuchaai", english: "man", pos: "noun", category: "family & people", art: {type:"emoji", char:"👨"} },
  { rank: 87, thai: "ผู้หญิง", roman: "phûuyǐng", english: "woman", pos: "noun", category: "family & people", art: {type:"emoji", char:"👩"} },
  { rank: 88, thai: "เด็ก", roman: "dèk", english: "kid, child", pos: "noun", category: "family & people", art: {type:"emoji", char:"🧒"} },
  { rank: 89, thai: "ครอบครัว", roman: "khrôopkhrua", english: "family", pos: "noun", category: "family & people", art: {type:"emoji", char:"👨‍👩‍👧"} },
  { rank: 90, thai: "สามี", roman: "sǎamii", english: "husband", pos: "noun", category: "family & people", art: {type:"emoji", char:"🤵"} },
  { rank: 91, thai: "ภรรยา", roman: "phanrayaa", english: "wife", pos: "noun", category: "family & people", art: {type:"emoji", char:"👰"} },
  { rank: 92, thai: "ปู่", roman: "pùu", english: "grandfather", pos: "noun", category: "family & people", art: {type:"emoji", char:"👴"} },
  { rank: 93, thai: "ย่า", roman: "yâa", english: "grandmother", pos: "noun", category: "family & people", art: {type:"emoji", char:"👵"} },
  { rank: 94, thai: "แฟน", roman: "faen", english: "partner, boyfriend or girlfriend", pos: "noun", category: "family & people", art: {type:"emoji", char:"💑"} },
  { rank: 95, thai: "คุณ", roman: "khun", english: "you (polite)", pos: "pronoun", category: "pronouns", art: {type:"text", gloss:"you (polite)"} },
  { rank: 96, thai: "ผม", roman: "phǒm", english: "I, me (male speaker)", pos: "pronoun", category: "pronouns", art: {type:"text", gloss:"I / me (male)"} },
  { rank: 97, thai: "ฉัน", roman: "chǎn", english: "I, me (female speaker)", pos: "pronoun", category: "pronouns", art: {type:"text", gloss:"I / me (female)"} },
  { rank: 98, thai: "เขา", roman: "khǎo", english: "he, she, they", pos: "pronoun", category: "pronouns", art: {type:"text", gloss:"he / she / they"} },
  { rank: 99, thai: "มัน", roman: "man", english: "it", pos: "pronoun", category: "pronouns", art: {type:"text", gloss:"it"} },
  { rank: 100, thai: "ท่าน", roman: "thâan", english: "you (formal)", pos: "pronoun", category: "pronouns", art: {type:"text", gloss:"you (formal)"} },
  { rank: 101, thai: "หัว", roman: "hǔa", english: "head", pos: "noun", category: "body", art: {type:"glyph", icon:"head"} },
  { rank: 102, thai: "ตา", roman: "taa", english: "eye", pos: "noun", category: "body", art: {type:"emoji", char:"👁️"} },
  { rank: 103, thai: "หู", roman: "hǔu", english: "ear", pos: "noun", category: "body", art: {type:"emoji", char:"👂"} },
  { rank: 104, thai: "จมูก", roman: "chamùuk", english: "nose", pos: "noun", category: "body", art: {type:"emoji", char:"👃"} },
  { rank: 105, thai: "ปาก", roman: "pàak", english: "mouth", pos: "noun", category: "body", art: {type:"emoji", char:"👄"} },
  { rank: 106, thai: "ฟัน", roman: "fan", english: "tooth", pos: "noun", category: "body", art: {type:"emoji", char:"🦷"} },
  { rank: 107, thai: "มือ", roman: "mue", english: "hand", pos: "noun", category: "body", art: {type:"emoji", char:"✋"} },
  { rank: 108, thai: "เท้า", roman: "tháo", english: "foot", pos: "noun", category: "body", art: {type:"emoji", char:"🦶"} },
  { rank: 109, thai: "ขา", roman: "khǎa", english: "leg", pos: "noun", category: "body", art: {type:"emoji", char:"🦵"} },
  { rank: 110, thai: "แขน", roman: "khǎen", english: "arm", pos: "noun", category: "body", art: {type:"emoji", char:"💪"} },
  { rank: 111, thai: "นิ้ว", roman: "níu", english: "finger", pos: "noun", category: "body", art: {type:"emoji", char:"☝️"} },
  { rank: 112, thai: "หน้า", roman: "nâa", english: "face, front, page", pos: "noun", category: "body", art: {type:"glyph", icon:"head", mod:"eye"} },
  { rank: 113, thai: "ท้อง", roman: "thóong", english: "stomach, belly", pos: "noun", category: "body", art: {type:"glyph", icon:"bowl", mod:"person"} },
  { rank: 114, thai: "หลัง", roman: "lǎng", english: "back, behind", pos: "noun", category: "body", art: {type:"glyph", icon:"person", mod:"arrow-left"} },
  { rank: 115, thai: "ใจ", roman: "chai", english: "heart, mind", pos: "noun", category: "body", art: {type:"emoji", char:"❤️"} },
  { rank: 116, thai: "เลือด", roman: "lûeat", english: "blood", pos: "noun", category: "body", art: {type:"emoji", char:"🩸"} },
  { rank: 117, thai: "กระดูก", roman: "kradùuk", english: "bone", pos: "noun", category: "body", art: {type:"emoji", char:"🦴"} },
  { rank: 118, thai: "ผิว", roman: "phǐu", english: "skin", pos: "noun", category: "body", art: {type:"glyph", icon:"hand", mod:"grid"} },
  { rank: 119, thai: "คอ", roman: "khoo", english: "neck, throat", pos: "noun", category: "body", art: {type:"glyph", icon:"head", mod:"minus"} },
  { rank: 120, thai: "อะไร", roman: "àrai", english: "what", pos: "question", category: "question words", art: {type:"text", gloss:"what?"} },
  { rank: 121, thai: "ใคร", roman: "khrai", english: "who", pos: "question", category: "question words", art: {type:"text", gloss:"who?"} },
  { rank: 122, thai: "ที่ไหน", roman: "thîinǎi", english: "where", pos: "question", category: "question words", art: {type:"text", gloss:"where?"} },
  { rank: 123, thai: "เมื่อไหร่", roman: "mûearài", english: "when?", pos: "question", category: "question words", art: {type:"text", gloss:"when?"} },
  { rank: 124, thai: "ทำไม", roman: "thammai", english: "why", pos: "question", category: "question words", art: {type:"text", gloss:"why?"} },
  { rank: 125, thai: "อย่างไร", roman: "yàangrai", english: "how", pos: "question", category: "question words", art: {type:"text", gloss:"how?"} },
  { rank: 126, thai: "หนึ่ง", roman: "nùeng", english: "one", pos: "number", category: "numbers", art: {type:"emoji", char:"1️⃣"} },
  { rank: 127, thai: "สอง", roman: "sǒong", english: "two", pos: "number", category: "numbers", art: {type:"emoji", char:"2️⃣"} },
  { rank: 128, thai: "สาม", roman: "sǎam", english: "three", pos: "number", category: "numbers", art: {type:"emoji", char:"3️⃣"} },
  { rank: 129, thai: "สี่", roman: "sìi", english: "four", pos: "number", category: "numbers", art: {type:"emoji", char:"4️⃣"} },
  { rank: 130, thai: "ห้า", roman: "hâa", english: "five", pos: "number", category: "numbers", art: {type:"emoji", char:"5️⃣"} },
  { rank: 131, thai: "หก", roman: "hòk", english: "six", pos: "number", category: "numbers", art: {type:"emoji", char:"6️⃣"} },
  { rank: 132, thai: "เจ็ด", roman: "chèt", english: "seven", pos: "number", category: "numbers", art: {type:"emoji", char:"7️⃣"} },
  { rank: 133, thai: "แปด", roman: "pàet", english: "eight", pos: "number", category: "numbers", art: {type:"emoji", char:"8️⃣"} },
  { rank: 134, thai: "เก้า", roman: "kâo", english: "nine", pos: "number", category: "numbers", art: {type:"emoji", char:"9️⃣"} },
  { rank: 135, thai: "สิบ", roman: "sìp", english: "ten", pos: "number", category: "numbers", art: {type:"emoji", char:"🔟"} },
  { rank: 136, thai: "ศูนย์", roman: "sǔun", english: "zero", pos: "number", category: "numbers", art: {type:"emoji", char:"0️⃣"} },
  { rank: 137, thai: "ร้อย", roman: "rói", english: "hundred", pos: "number", category: "numbers", art: {type:"text", gloss:"100"} },
  { rank: 138, thai: "พัน", roman: "phan", english: "thousand", pos: "number", category: "numbers", art: {type:"text", gloss:"1,000"} },
  { rank: 139, thai: "หมื่น", roman: "mùen", english: "ten thousand", pos: "number", category: "numbers", art: {type:"text", gloss:"10,000"} },
  { rank: 140, thai: "แสน", roman: "sǎen", english: "hundred thousand", pos: "number", category: "numbers", art: {type:"text", gloss:"100,000"} },
  { rank: 141, thai: "ล้าน", roman: "láan", english: "million", pos: "number", category: "numbers", art: {type:"text", gloss:"1,000,000"} },
  { rank: 142, thai: "ครึ่ง", roman: "khrûeng", english: "half", pos: "number", category: "numbers", art: {type:"glyph", icon:"pie", mod:"minus"} },
  { rank: 143, thai: "สี", roman: "sǐi", english: "color", pos: "noun", category: "colors", art: {type:"emoji", char:"🎨"} },
  { rank: 144, thai: "แดง", roman: "daeng", english: "red", pos: "adjective", category: "colors", art: {type:"emoji", char:"🔴"} },
  { rank: 145, thai: "เขียว", roman: "khǐao", english: "green", pos: "adjective", category: "colors", art: {type:"emoji", char:"🟢"} },
  { rank: 146, thai: "น้ำเงิน", roman: "námngoen", english: "blue", pos: "adjective", category: "colors", art: {type:"emoji", char:"🔵"} },
  { rank: 147, thai: "เหลือง", roman: "lǔeang", english: "yellow", pos: "adjective", category: "colors", art: {type:"emoji", char:"🟡"} },
  { rank: 148, thai: "ดำ", roman: "dam", english: "black", pos: "adjective", category: "colors", art: {type:"emoji", char:"⚫"} },
  { rank: 149, thai: "ขาว", roman: "khǎao", english: "white", pos: "adjective", category: "colors", art: {type:"emoji", char:"⚪"} },
  { rank: 150, thai: "ส้ม", roman: "sôm", english: "orange (colour)", pos: "adjective", category: "colors", art: {type:"emoji", char:"🟠"} },
  { rank: 151, thai: "ชมพู", roman: "chomphuu", english: "pink", pos: "adjective", category: "colors", art: {type:"emoji", char:"🩷"} },
  { rank: 152, thai: "ม่วง", roman: "mûang", english: "purple", pos: "adjective", category: "colors", art: {type:"emoji", char:"🟣"} },
  { rank: 153, thai: "น้ำตาล", roman: "námtaan", english: "brown, sugar", pos: "adjective", category: "colors", art: {type:"emoji", char:"🟤"} },
  { rank: 154, thai: "เทา", roman: "thao", english: "grey", pos: "adjective", category: "colors", art: {type:"emoji", char:"🩶"} },
  { rank: 155, thai: "ข้าว", roman: "khâao", english: "rice", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🍚"} },
  { rank: 156, thai: "อาหาร", roman: "aahǎan", english: "food", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🍲"} },
  { rank: 157, thai: "เนื้อ", roman: "núea", english: "meat", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🥩"} },
  { rank: 158, thai: "ไก่", roman: "kài", english: "chicken", pos: "noun", category: "animals", art: {type:"emoji", char:"🐔"} },
  { rank: 159, thai: "หมู", roman: "mǔu", english: "pig, pork", pos: "noun", category: "animals", art: {type:"emoji", char:"🐖"} },
  { rank: 160, thai: "ปลา", roman: "plaa", english: "fish", pos: "noun", category: "animals", art: {type:"emoji", char:"🐟"} },
  { rank: 161, thai: "ไข่", roman: "khài", english: "egg", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🥚"} },
  { rank: 162, thai: "ผัก", roman: "phàk", english: "vegetable", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🥦"} },
  { rank: 163, thai: "ผลไม้", roman: "phǒnlamáai", english: "fruit", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🍎"} },
  { rank: 164, thai: "นม", roman: "nom", english: "milk", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🥛"} },
  { rank: 165, thai: "กาแฟ", roman: "kaafae", english: "coffee", pos: "noun", category: "food & drink", art: {type:"emoji", char:"☕"} },
  { rank: 166, thai: "ชา", roman: "chaa", english: "tea", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🍵"} },
  { rank: 167, thai: "เบียร์", roman: "bia", english: "beer", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🍺"} },
  { rank: 168, thai: "ขนม", roman: "khanǒm", english: "snack, sweets", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🍬"} },
  { rank: 169, thai: "เกลือ", roman: "kluea", english: "salt", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🧂"} },
  { rank: 170, thai: "พริก", roman: "phrík", english: "chilli", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🌶️"} },
  { rank: 171, thai: "ก๋วยเตี๋ยว", roman: "kǔaitǐao", english: "noodle soup", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🍜"} },
  { rank: 172, thai: "ขนมปัง", roman: "khanǒmpang", english: "bread", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🍞"} },
  { rank: 173, thai: "กล้วย", roman: "klûai", english: "banana", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🍌"} },
  { rank: 174, thai: "มะม่วง", roman: "mamûang", english: "mango", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🥭"} },
  { rank: 175, thai: "แตงโม", roman: "taengmoo", english: "watermelon", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🍉"} },
  { rank: 176, thai: "น้ำแข็ง", roman: "námkhǎeng", english: "ice", pos: "noun", category: "food & drink", art: {type:"emoji", char:"🧊"} },
  { rank: 177, thai: "กิน", roman: "kin", english: "to eat", pos: "verb", category: "verbs", art: {type:"glyph", icon:"bowl"} },
  { rank: 178, thai: "ดื่ม", roman: "dùem", english: "to drink", pos: "verb", category: "verbs", art: {type:"glyph", icon:"cup"} },
  { rank: 179, thai: "หิว", roman: "hǐu", english: "hungry", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"bowl", mod:"minus"} },
  { rank: 180, thai: "อิ่ม", roman: "ìm", english: "full (from eating)", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"bowl", mod:"check"} },
  { rank: 181, thai: "อร่อย", roman: "aròi", english: "delicious", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"bowl", mod:"heart"} },
  { rank: 182, thai: "เผ็ด", roman: "phèt", english: "spicy", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"fire", mod:"mouth"} },
  { rank: 183, thai: "หวาน", roman: "wǎan", english: "sweet", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"mouth", mod:"heart"} },
  { rank: 184, thai: "เปรี้ยว", roman: "prîao", english: "sour", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"mouth", mod:"spark"} },
  { rank: 185, thai: "เค็ม", roman: "khem", english: "salty", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"mouth", mod:"grid"} },
  { rank: 186, thai: "ขม", roman: "khǒm", english: "bitter", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"mouth", mod:"minus"} },
  { rank: 187, thai: "หมา", roman: "mǎa", english: "dog", pos: "noun", category: "animals", art: {type:"emoji", char:"🐕"} },
  { rank: 188, thai: "แมว", roman: "maeo", english: "cat", pos: "noun", category: "animals", art: {type:"emoji", char:"🐈"} },
  { rank: 189, thai: "นก", roman: "nók", english: "bird", pos: "noun", category: "animals", art: {type:"emoji", char:"🐦"} },
  { rank: 190, thai: "ช้าง", roman: "cháang", english: "elephant", pos: "noun", category: "animals", art: {type:"emoji", char:"🐘"} },
  { rank: 191, thai: "ม้า", roman: "máa", english: "horse", pos: "noun", category: "animals", art: {type:"emoji", char:"🐎"} },
  { rank: 192, thai: "วัว", roman: "wua", english: "cow", pos: "noun", category: "animals", art: {type:"emoji", char:"🐄"} },
  { rank: 193, thai: "เสือ", roman: "sǔea", english: "tiger", pos: "noun", category: "animals", art: {type:"emoji", char:"🐅"} },
  { rank: 194, thai: "ลิง", roman: "ling", english: "monkey", pos: "noun", category: "animals", art: {type:"emoji", char:"🐒"} },
  { rank: 195, thai: "งู", roman: "nguu", english: "snake", pos: "noun", category: "animals", art: {type:"emoji", char:"🐍"} },
  { rank: 196, thai: "หนู", roman: "nǔu", english: "mouse, rat", pos: "noun", category: "animals", art: {type:"emoji", char:"🐁"} },
  { rank: 197, thai: "แมลง", roman: "malaeng", english: "insect", pos: "noun", category: "animals", art: {type:"emoji", char:"🐛"} },
  { rank: 198, thai: "ยุง", roman: "yung", english: "mosquito", pos: "noun", category: "animals", art: {type:"emoji", char:"🦟"} },
  { rank: 199, thai: "เป็ด", roman: "pèt", english: "duck", pos: "noun", category: "animals", art: {type:"emoji", char:"🦆"} },
  { rank: 200, thai: "กบ", roman: "kòp", english: "frog", pos: "noun", category: "animals", art: {type:"emoji", char:"🐸"} },
  { rank: 201, thai: "ควาย", roman: "khwaai", english: "buffalo", pos: "noun", category: "animals", art: {type:"emoji", char:"🐃"} },
  { rank: 202, thai: "กระต่าย", roman: "kratàai", english: "rabbit", pos: "noun", category: "animals", art: {type:"emoji", char:"🐇"} },
  { rank: 203, thai: "เต่า", roman: "tào", english: "turtle", pos: "noun", category: "animals", art: {type:"emoji", char:"🐢"} },
  { rank: 204, thai: "ปู", roman: "puu", english: "crab", pos: "noun", category: "animals", art: {type:"emoji", char:"🦀"} },
  { rank: 205, thai: "กุ้ง", roman: "kûng", english: "shrimp", pos: "noun", category: "animals", art: {type:"emoji", char:"🦐"} },
  { rank: 206, thai: "ผีเสื้อ", roman: "phǐisûea", english: "butterfly", pos: "noun", category: "animals", art: {type:"emoji", char:"🦋"} },
  { rank: 207, thai: "มด", roman: "mót", english: "ant", pos: "noun", category: "animals", art: {type:"emoji", char:"🐜"} },
  { rank: 208, thai: "สัตว์", roman: "sàt", english: "animal", pos: "noun", category: "animals", art: {type:"emoji", char:"🐾"} },
  { rank: 209, thai: "วัน", roman: "wan", english: "day", pos: "noun", category: "time & dates", art: {type:"emoji", char:"📅"} },
  { rank: 210, thai: "เดือน", roman: "duean", english: "month", pos: "noun", category: "time & dates", art: {type:"emoji", char:"🗓️"} },
  { rank: 211, thai: "ปี", roman: "pii", english: "year", pos: "noun", category: "time & dates", art: {type:"glyph", icon:"calendar", mod:"star"} },
  { rank: 212, thai: "ชั่วโมง", roman: "chûamoong", english: "hour", pos: "noun", category: "time & dates", art: {type:"glyph", icon:"clock"} },
  { rank: 213, thai: "นาที", roman: "naathii", english: "minute", pos: "noun", category: "time & dates", art: {type:"glyph", icon:"clock", mod:"minus"} },
  { rank: 214, thai: "เวลา", roman: "weelaa", english: "time", pos: "noun", category: "time & dates", art: {type:"emoji", char:"⏰"} },
  { rank: 215, thai: "วันนี้", roman: "wanníi", english: "today", pos: "noun", category: "time & dates", art: {type:"glyph", icon:"calendar", mod:"check"} },
  { rank: 216, thai: "พรุ่งนี้", roman: "phrûngníi", english: "tomorrow", pos: "noun", category: "time & dates", art: {type:"glyph", icon:"calendar", mod:"arrow-right"} },
  { rank: 217, thai: "เมื่อวาน", roman: "mûeawaan", english: "yesterday", pos: "noun", category: "time & dates", art: {type:"glyph", icon:"calendar", mod:"arrow-left"} },
  { rank: 218, thai: "เช้า", roman: "cháo", english: "morning", pos: "noun", category: "time & dates", art: {type:"emoji", char:"🌅"} },
  { rank: 219, thai: "เที่ยง", roman: "thîang", english: "noon", pos: "noun", category: "time & dates", art: {type:"emoji", char:"🌞"} },
  { rank: 220, thai: "บ่าย", roman: "bàai", english: "afternoon", pos: "noun", category: "time & dates", art: {type:"glyph", icon:"sun", mod:"arrow-down"} },
  { rank: 221, thai: "เย็น", roman: "yen", english: "evening, cool", pos: "noun", category: "time & dates", art: {type:"emoji", char:"🌇"} },
  { rank: 222, thai: "คืน", roman: "khuun", english: "night", pos: "noun", category: "time & dates", art: {type:"emoji", char:"🌃"} },
  { rank: 223, thai: "สัปดาห์", roman: "sàpdaa", english: "week", pos: "noun", category: "time & dates", art: {type:"glyph", icon:"calendar", mod:"grid"} },
  { rank: 224, thai: "ตอนนี้", roman: "toonníi", english: "now", pos: "adverb", category: "time & dates", art: {type:"glyph", icon:"clock", mod:"bolt"} },
  { rank: 225, thai: "ก่อน", roman: "kòon", english: "before", pos: "prep", category: "time & dates", art: {type:"glyph", icon:"clock", mod:"arrow-left"} },
  { rank: 226, thai: "หลังจาก", roman: "lǎngchàak", english: "after", pos: "prep", category: "time & dates", art: {type:"glyph", icon:"clock", mod:"arrow-right"} },
  { rank: 227, thai: "วันจันทร์", roman: "wanchan", english: "Monday", pos: "noun", category: "time & dates", art: {type:"text", gloss:"Mon"} },
  { rank: 228, thai: "วันอังคาร", roman: "wan-angkhaan", english: "Tuesday", pos: "noun", category: "time & dates", art: {type:"text", gloss:"Tue"} },
  { rank: 229, thai: "วันพุธ", roman: "wanphút", english: "Wednesday", pos: "noun", category: "time & dates", art: {type:"text", gloss:"Wed"} },
  { rank: 230, thai: "วันพฤหัส", roman: "wanpharúehàt", english: "Thursday", pos: "noun", category: "time & dates", art: {type:"text", gloss:"Thu"} },
  { rank: 231, thai: "วันศุกร์", roman: "wansùk", english: "Friday", pos: "noun", category: "time & dates", art: {type:"text", gloss:"Fri"} },
  { rank: 232, thai: "วันเสาร์", roman: "wansǎo", english: "Saturday", pos: "noun", category: "time & dates", art: {type:"text", gloss:"Sat"} },
  { rank: 233, thai: "วันอาทิตย์", roman: "wan-aathít", english: "Sunday", pos: "noun", category: "time & dates", art: {type:"text", gloss:"Sun"} },
  { rank: 234, thai: "รถ", roman: "rót", english: "car, vehicle", pos: "noun", category: "transport", art: {type:"emoji", char:"🚗"} },
  { rank: 235, thai: "รถไฟ", roman: "rótfai", english: "train", pos: "noun", category: "transport", art: {type:"emoji", char:"🚆"} },
  { rank: 236, thai: "รถเมล์", roman: "rótmee", english: "bus", pos: "noun", category: "transport", art: {type:"emoji", char:"🚌"} },
  { rank: 237, thai: "เครื่องบิน", roman: "khrûeangbin", english: "aeroplane", pos: "noun", category: "transport", art: {type:"emoji", char:"✈️"} },
  { rank: 238, thai: "เรือ", roman: "ruea", english: "boat", pos: "noun", category: "transport", art: {type:"emoji", char:"🚢"} },
  { rank: 239, thai: "จักรยาน", roman: "chàkkrayaan", english: "bicycle", pos: "noun", category: "transport", art: {type:"emoji", char:"🚲"} },
  { rank: 240, thai: "มอเตอร์ไซค์", roman: "mootoesai", english: "motorcycle", pos: "noun", category: "transport", art: {type:"emoji", char:"🏍️"} },
  { rank: 241, thai: "แท็กซี่", roman: "tháeksîi", english: "taxi", pos: "noun", category: "transport", art: {type:"emoji", char:"🚕"} },
  { rank: 242, thai: "รถไฟฟ้า", roman: "rótfaifáa", english: "skytrain", pos: "noun", category: "transport", art: {type:"emoji", char:"🚈"} },
  { rank: 243, thai: "สถานี", roman: "sathǎanii", english: "station", pos: "noun", category: "transport", art: {type:"emoji", char:"🚉"} },
  { rank: 244, thai: "ตั๋ว", roman: "tǔa", english: "ticket", pos: "noun", category: "transport", art: {type:"emoji", char:"🎫"} },
  { rank: 245, thai: "ขับ", roman: "khàp", english: "to drive", pos: "verb", category: "verbs", art: {type:"glyph", icon:"grid", mod:"arrow-right"} },
  { rank: 246, thai: "ขี่", roman: "khìi", english: "to ride", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person", mod:"arrow-cycle"} },
  { rank: 247, thai: "เดิน", roman: "doen", english: "to walk", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person", mod:"arrow-right"} },
  { rank: 248, thai: "วิ่ง", roman: "wîng", english: "to run", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person-run"} },
  { rank: 249, thai: "บิน", roman: "bin", english: "to fly", pos: "verb", category: "verbs", art: {type:"glyph", icon:"cloud", mod:"arrow-right"} },
  { rank: 250, thai: "ว่าย", roman: "wâai", english: "to swim", pos: "verb", category: "verbs", art: {type:"glyph", icon:"wave", mod:"person"} },
  { rank: 251, thai: "นั่ง", roman: "nâng", english: "to sit", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person-sit"} },
  { rank: 252, thai: "ยืน", roman: "yuun", english: "to stand", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person", mod:"bars"} },
  { rank: 253, thai: "นอน", roman: "noon", english: "to sleep, to lie down", pos: "verb", category: "verbs", art: {type:"glyph", icon:"bed"} },
  { rank: 254, thai: "ตื่น", roman: "tùen", english: "to wake up", pos: "verb", category: "verbs", art: {type:"glyph", icon:"bed", mod:"bolt"} },
  { rank: 255, thai: "ซื้อ", roman: "súe", english: "to buy", pos: "verb", category: "verbs", art: {type:"glyph", icon:"bag", mod:"plus"} },
  { rank: 256, thai: "ขาย", roman: "khǎai", english: "to sell", pos: "verb", category: "verbs", art: {type:"glyph", icon:"bag", mod:"coin"} },
  { rank: 257, thai: "จ่าย", roman: "chàai", english: "to pay", pos: "verb", category: "verbs", art: {type:"glyph", icon:"coin", mod:"arrow-right"} },
  { rank: 258, thai: "เงิน", roman: "ngoen", english: "money, silver", pos: "noun", category: "objects", art: {type:"emoji", char:"💰"} },
  { rank: 259, thai: "หนังสือ", roman: "nǎngsǔe", english: "book", pos: "noun", category: "objects", art: {type:"emoji", char:"📕"} },
  { rank: 260, thai: "โทรศัพท์", roman: "thoorasàp", english: "telephone", pos: "noun", category: "objects", art: {type:"emoji", char:"📱"} },
  { rank: 261, thai: "คอมพิวเตอร์", roman: "khoomphiutôe", english: "computer", pos: "noun", category: "objects", art: {type:"emoji", char:"💻"} },
  { rank: 262, thai: "โต๊ะ", roman: "tó", english: "table, desk", pos: "noun", category: "objects", art: {type:"glyph", icon:"grid", mod:"box"} },
  { rank: 263, thai: "เก้าอี้", roman: "kâo-îi", english: "chair", pos: "noun", category: "objects", art: {type:"emoji", char:"🪑"} },
  { rank: 264, thai: "ประตู", roman: "pratuu", english: "door", pos: "noun", category: "objects", art: {type:"emoji", char:"🚪"} },
  { rank: 265, thai: "หน้าต่าง", roman: "nâataang", english: "window", pos: "noun", category: "objects", art: {type:"emoji", char:"🪟"} },
  { rank: 266, thai: "เตียง", roman: "tiang", english: "bed", pos: "noun", category: "objects", art: {type:"emoji", char:"🛏️"} },
  { rank: 267, thai: "เสื้อ", roman: "sûea", english: "shirt", pos: "noun", category: "objects", art: {type:"emoji", char:"👕"} },
  { rank: 268, thai: "กางเกง", roman: "kaangkeeng", english: "trousers", pos: "noun", category: "objects", art: {type:"emoji", char:"👖"} },
  { rank: 269, thai: "รองเท้า", roman: "roongtháo", english: "shoes", pos: "noun", category: "objects", art: {type:"emoji", char:"👟"} },
  { rank: 270, thai: "หมวก", roman: "mùak", english: "hat", pos: "noun", category: "objects", art: {type:"emoji", char:"🧢"} },
  { rank: 271, thai: "กระเป๋า", roman: "krapǎo", english: "bag", pos: "noun", category: "objects", art: {type:"emoji", char:"👜"} },
  { rank: 272, thai: "นาฬิกา", roman: "naalíkaa", english: "clock, watch", pos: "noun", category: "objects", art: {type:"emoji", char:"⌚"} },
  { rank: 273, thai: "กุญแจ", roman: "kunchae", english: "key", pos: "noun", category: "objects", art: {type:"emoji", char:"🔑"} },
  { rank: 274, thai: "ไฟฟ้า", roman: "faifáa", english: "electricity", pos: "noun", category: "objects", art: {type:"emoji", char:"💡"} },
  { rank: 275, thai: "ปากกา", roman: "paakkaa", english: "pen", pos: "noun", category: "objects", art: {type:"emoji", char:"🖊️"} },
  { rank: 276, thai: "ดินสอ", roman: "dinsǒo", english: "pencil", pos: "noun", category: "objects", art: {type:"emoji", char:"✏️"} },
  { rank: 277, thai: "กระดาษ", roman: "kradàat", english: "paper", pos: "noun", category: "objects", art: {type:"emoji", char:"📄"} },
  { rank: 278, thai: "จดหมาย", roman: "chòtmǎai", english: "letter (mail)", pos: "noun", category: "objects", art: {type:"emoji", char:"✉️"} },
  { rank: 279, thai: "รูป", roman: "rûup", english: "picture, photo", pos: "noun", category: "objects", art: {type:"emoji", char:"🖼️"} },
  { rank: 280, thai: "เพลง", roman: "phleeng", english: "song", pos: "noun", category: "objects", art: {type:"emoji", char:"🎵"} },
  { rank: 281, thai: "หนัง", roman: "nǎng", english: "film, movie", pos: "noun", category: "objects", art: {type:"emoji", char:"🎬"} },
  { rank: 282, thai: "ทีวี", roman: "thiiwii", english: "television", pos: "noun", category: "objects", art: {type:"emoji", char:"📺"} },
  { rank: 283, thai: "ของขวัญ", roman: "khǒongkhwǎn", english: "gift", pos: "noun", category: "objects", art: {type:"emoji", char:"🎁"} },
  { rank: 284, thai: "รัก", roman: "rák", english: "to love", pos: "verb", category: "verbs", art: {type:"glyph", icon:"heart"} },
  { rank: 285, thai: "ชอบ", roman: "chôop", english: "to like", pos: "verb", category: "verbs", art: {type:"glyph", icon:"heart", mod:"check"} },
  { rank: 286, thai: "เกลียด", roman: "klìat", english: "to hate", pos: "verb", category: "verbs", art: {type:"glyph", icon:"heart-broken"} },
  { rank: 287, thai: "อยาก", roman: "yàak", english: "to want to", pos: "verb", category: "verbs", art: {type:"glyph", icon:"thought", mod:"heart"} },
  { rank: 288, thai: "ต้องการ", roman: "tôngkaan", english: "to need", pos: "verb", category: "verbs", art: {type:"glyph", icon:"target", mod:"hand"} },
  { rank: 289, thai: "ชื่อ", roman: "chûe", english: "name", pos: "noun", category: "abstract", art: {type:"glyph", icon:"note", mod:"person"} },
  { rank: 290, thai: "เรียก", roman: "rîak", english: "to call", pos: "verb", category: "verbs", art: {type:"glyph", icon:"speech", mod:"bell"} },
  { rank: 291, thai: "ถาม", roman: "thǎam", english: "to ask", pos: "verb", category: "verbs", art: {type:"glyph", icon:"question"} },
  { rank: 292, thai: "ตอบ", roman: "tòop", english: "to answer", pos: "verb", category: "verbs", art: {type:"glyph", icon:"speech", mod:"check"} },
  { rank: 293, thai: "ช่วย", roman: "chûai", english: "to help", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"heart"} },
  { rank: 294, thai: "รอ", roman: "roo", english: "to wait", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hourglass"} },
  { rank: 295, thai: "หา", roman: "hǎa", english: "to look for", pos: "verb", category: "verbs", art: {type:"glyph", icon:"magnify"} },
  { rank: 296, thai: "เจอ", roman: "choe", english: "to meet, to find", pos: "verb", category: "verbs", art: {type:"glyph", icon:"people", mod:"check"} },
  { rank: 297, thai: "เปิด", roman: "pòet", english: "to open, to turn on", pos: "verb", category: "verbs", art: {type:"glyph", icon:"door", mod:"arrow-right"} },
  { rank: 298, thai: "ปิด", roman: "pìt", english: "to close, to turn off", pos: "verb", category: "verbs", art: {type:"glyph", icon:"door", mod:"cross"} },
  { rank: 299, thai: "เข้า", roman: "khâo", english: "to enter", pos: "verb", category: "verbs", art: {type:"glyph", icon:"arrow-right", mod:"house"} },
  { rank: 300, thai: "ออก", roman: "òok", english: "to go out, to exit", pos: "verb", category: "verbs", art: {type:"glyph", icon:"arrow-left", mod:"house"} },
  { rank: 301, thai: "ขึ้น", roman: "khûen", english: "to go up", pos: "verb", category: "verbs", art: {type:"glyph", icon:"arrow-up"} },
  { rank: 302, thai: "ลง", roman: "long", english: "to go down", pos: "verb", category: "verbs", art: {type:"glyph", icon:"arrow-down"} },
  { rank: 303, thai: "กลับ", roman: "klàp", english: "to return", pos: "verb", category: "verbs", art: {type:"glyph", icon:"arrow-cycle"} },
  { rank: 304, thai: "ส่ง", roman: "sòng", english: "to send", pos: "verb", category: "verbs", art: {type:"glyph", icon:"note", mod:"arrow-right"} },
  { rank: 305, thai: "รับ", roman: "ráp", english: "to receive", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"arrow-down"} },
  { rank: 306, thai: "เอา", roman: "ao", english: "to take", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"arrow-left"} },
  { rank: 307, thai: "วาง", roman: "waang", english: "to put down", pos: "verb", category: "verbs", art: {type:"glyph", icon:"box", mod:"arrow-down"} },
  { rank: 308, thai: "ถือ", roman: "thǔe", english: "to hold, to carry", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"box"} },
  { rank: 309, thai: "สวย", roman: "sǔai", english: "beautiful", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"spark", mod:"smile"} },
  { rank: 310, thai: "หล่อ", roman: "lòo", english: "handsome", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"person", mod:"star"} },
  { rank: 311, thai: "น่ารัก", roman: "nâarák", english: "cute", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"heart", mod:"smile"} },
  { rank: 312, thai: "ร้อน", roman: "róon", english: "hot", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"fire"} },
  { rank: 313, thai: "หนาว", roman: "nǎao", english: "cold (weather)", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"snow"} },
  { rank: 314, thai: "อุ่น", roman: "ùn", english: "warm", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"fire", mod:"minus"} },
  { rank: 315, thai: "สูง", roman: "sǔung", english: "tall, high", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"bars", mod:"arrow-up"} },
  { rank: 316, thai: "เตี้ย", roman: "tîa", english: "short (in height)", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"bars", mod:"arrow-down"} },
  { rank: 317, thai: "ยาว", roman: "yaao", english: "long", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"ruler", mod:"arrow-right"} },
  { rank: 318, thai: "สั้น", roman: "sân", english: "short (in length)", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"ruler", mod:"minus"} },
  { rank: 319, thai: "อ้วน", roman: "ûan", english: "fat", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"person", mod:"plus"} },
  { rank: 320, thai: "ผอม", roman: "phǒom", english: "thin (of a person)", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"person", mod:"minus"} },
  { rank: 321, thai: "แพง", roman: "phaeng", english: "expensive", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"coin", mod:"arrow-up"} },
  { rank: 322, thai: "ถูก", roman: "thùuk", english: "cheap, correct", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"coin", mod:"arrow-down"} },
  { rank: 323, thai: "ง่าย", roman: "ngâai", english: "easy", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"check", mod:"smile"} },
  { rank: 324, thai: "ยาก", roman: "yâak", english: "difficult", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"exclaim", mod:"brain"} },
  { rank: 325, thai: "เร็ว", roman: "reo", english: "fast", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"bolt"} },
  { rank: 326, thai: "ช้า", roman: "cháa", english: "slow", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"clock", mod:"arrow-down"} },
  { rank: 327, thai: "แข็งแรง", roman: "khǎengraeng", english: "strong", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"shield", mod:"bolt"} },
  { rank: 328, thai: "อ่อน", roman: "òon", english: "weak, soft", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"cloud", mod:"minus"} },
  { rank: 329, thai: "สะอาด", roman: "sa-àat", english: "clean", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"spark", mod:"check"} },
  { rank: 330, thai: "สกปรก", roman: "sòkkapròk", english: "dirty", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"spark", mod:"cross"} },
  { rank: 331, thai: "ดัง", roman: "dang", english: "loud, famous", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"bell", mod:"plus"} },
  { rank: 332, thai: "เงียบ", roman: "ngîap", english: "quiet", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"bell", mod:"ban"} },
  { rank: 333, thai: "สนุก", roman: "sanùk", english: "fun", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"smile", mod:"star"} },
  { rank: 334, thai: "ดีใจ", roman: "diichai", english: "glad", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"smile", mod:"heart"} },
  { rank: 335, thai: "เสียใจ", roman: "sǐachai", english: "sad", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"frown"} },
  { rank: 336, thai: "โกรธ", roman: "kròot", english: "angry", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"frown", mod:"fire"} },
  { rank: 337, thai: "กลัว", roman: "klua", english: "afraid", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"frown", mod:"bolt"} },
  { rank: 338, thai: "เหนื่อย", roman: "nùeay", english: "tired", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"hourglass", mod:"person"} },
  { rank: 339, thai: "ง่วง", roman: "ngûang", english: "sleepy", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"bed", mod:"moon"} },
  { rank: 340, thai: "สบาย", roman: "sabaai", english: "comfortable, well", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"smile", mod:"cloud"} },
  { rank: 341, thai: "ป่วย", roman: "pùai", english: "sick", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"person", mod:"exclaim"} },
  { rank: 342, thai: "เจ็บ", roman: "chèp", english: "to hurt", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person", mod:"bolt"} },
  { rank: 343, thai: "หาย", roman: "hǎai", english: "to disappear, to recover", pos: "verb", category: "verbs", art: {type:"glyph", icon:"cloud", mod:"spark"} },
  { rank: 344, thai: "ตาย", roman: "taai", english: "to die", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person", mod:"cross"} },
  { rank: 345, thai: "เกิด", roman: "kòet", english: "to be born, to happen", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person", mod:"spark"} },
  { rank: 346, thai: "ชีวิต", roman: "chiiwít", english: "life", pos: "noun", category: "abstract", art: {type:"glyph", icon:"heart", mod:"spark"} },
  { rank: 347, thai: "ใจดี", roman: "chaidii", english: "kind", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"heart", mod:"hand"} },
  { rank: 348, thai: "เก่ง", roman: "kèng", english: "skilled, good at", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"medal", mod:"star"} },
  { rank: 349, thai: "ฉลาด", roman: "chalàat", english: "clever", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"brain", mod:"spark"} },
  { rank: 350, thai: "โง่", roman: "ngôo", english: "stupid", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"brain", mod:"minus"} },
  { rank: 351, thai: "ขยัน", roman: "khayǎn", english: "diligent", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"tool", mod:"spark"} },
  { rank: 352, thai: "รวย", roman: "ruai", english: "rich", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"coin", mod:"plus"} },
  { rank: 353, thai: "จน", roman: "chon", english: "poor, until", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"coin", mod:"minus"} },
  { rank: 354, thai: "ว่าง", roman: "wâang", english: "free, vacant", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"grid", mod:"minus"} },
  { rank: 355, thai: "ยุ่ง", roman: "yûng", english: "busy", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"grid", mod:"plus"} },
  { rank: 356, thai: "พร้อม", roman: "próom", english: "ready", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"check", mod:"flag"} },
  { rank: 357, thai: "เสร็จ", roman: "sèt", english: "finished", pos: "adjective", category: "adjectives", art: {type:"glyph", icon:"check", mod:"bars"} },
  { rank: 358, thai: "ด้วย", roman: "dûai", english: "also, with", pos: "adverb", category: "function words", art: {type:"text", gloss:"also / with"} },
  { rank: 359, thai: "เพื่อ", roman: "phûea", english: "in order to", pos: "conjunction", category: "function words", art: {type:"text", gloss:"in order to"} },
  { rank: 360, thai: "ถึง", roman: "thǔeng", english: "to reach, until", pos: "verb", category: "function words", art: {type:"text", gloss:"to / until"} },
  { rank: 361, thai: "จาก", roman: "chàak", english: "from", pos: "prep", category: "function words", art: {type:"text", gloss:"from"} },
  { rank: 362, thai: "โดย", roman: "dooi", english: "by", pos: "prep", category: "function words", art: {type:"text", gloss:"by"} },
  { rank: 363, thai: "ตาม", roman: "taam", english: "to follow, according to", pos: "verb", category: "verbs", art: {type:"glyph", icon:"people", mod:"arrow-right"} },
  { rank: 364, thai: "เกี่ยวกับ", roman: "kìaokàp", english: "about", pos: "prep", category: "function words", art: {type:"text", gloss:"about"} },
  { rank: 365, thai: "ระหว่าง", roman: "rawàang", english: "between, during", pos: "prep", category: "function words", art: {type:"text", gloss:"between"} },
  { rank: 366, thai: "นอกจาก", roman: "nôokchàak", english: "besides", pos: "prep", category: "function words", art: {type:"text", gloss:"besides"} },
  { rank: 367, thai: "บน", roman: "bon", english: "on, above", pos: "prep", category: "function words", art: {type:"text", gloss:"on / above"} },
  { rank: 368, thai: "ใต้", roman: "tâi", english: "under", pos: "prep", category: "function words", art: {type:"text", gloss:"under"} },
  { rank: 369, thai: "ข้าง", roman: "khâang", english: "side, beside", pos: "noun", category: "function words", art: {type:"text", gloss:"beside"} },
  { rank: 370, thai: "ใกล้", roman: "klâi", english: "near", pos: "adjective", category: "function words", art: {type:"text", gloss:"near"} },
  { rank: 371, thai: "ไกล", roman: "klai", english: "far", pos: "adjective", category: "function words", art: {type:"text", gloss:"far"} },
  { rank: 372, thai: "ทุก", roman: "thúk", english: "every", pos: "determiner", category: "function words", art: {type:"text", gloss:"every"} },
  { rank: 373, thai: "บาง", roman: "baang", english: "some", pos: "determiner", category: "function words", art: {type:"text", gloss:"some"} },
  { rank: 374, thai: "อื่น", roman: "ùen", english: "other", pos: "determiner", category: "function words", art: {type:"text", gloss:"other"} },
  { rank: 375, thai: "เอง", roman: "eeng", english: "oneself", pos: "pronoun", category: "pronouns", art: {type:"text", gloss:"-self"} },
  { rank: 376, thai: "กัน", roman: "kan", english: "together, each other", pos: "adverb", category: "function words", art: {type:"text", gloss:"together"} },
  { rank: 377, thai: "เท่า", roman: "thâo", english: "equal to", pos: "adverb", category: "function words", art: {type:"text", gloss:"as ... as"} },
  { rank: 378, thai: "กว่า", roman: "kwàa", english: "more than", pos: "adverb", category: "function words", art: {type:"text", gloss:"more than"} },
  { rank: 379, thai: "ที่สุด", roman: "thîisùt", english: "the most", pos: "adverb", category: "function words", art: {type:"text", gloss:"the most"} },
  { rank: 380, thai: "ยัง", roman: "yang", english: "still, yet", pos: "adverb", category: "function words", art: {type:"text", gloss:"still / yet"} },
  { rank: 381, thai: "เคย", roman: "khoei", english: "ever, used to", pos: "adverb", category: "function words", art: {type:"text", gloss:"ever / used to"} },
  { rank: 382, thai: "กำลัง", roman: "kamlang", english: "in progress", pos: "auxiliary", category: "function words", art: {type:"text", gloss:"-ing (right now)"} },
  { rank: 383, thai: "อาจ", roman: "àat", english: "may, might", pos: "auxiliary", category: "function words", art: {type:"text", gloss:"may / might"} },
  { rank: 384, thai: "คง", roman: "khong", english: "probably", pos: "adverb", category: "function words", art: {type:"text", gloss:"probably"} },
  { rank: 385, thai: "ควร", roman: "khuan", english: "should", pos: "auxiliary", category: "function words", art: {type:"text", gloss:"should"} },
  { rank: 386, thai: "ไหม", roman: "mǎi", english: "yes-no question particle", pos: "particle", category: "function words", art: {type:"text", gloss:"? (yes / no)"} },
  { rank: 387, thai: "ครับ", roman: "khráp", english: "polite particle (male)", pos: "particle", category: "function words", art: {type:"text", gloss:"polite (male)"} },
  { rank: 388, thai: "ค่ะ", roman: "khâ", english: "polite particle (female)", pos: "particle", category: "function words", art: {type:"text", gloss:"polite (female)"} },
  { rank: 389, thai: "นะ", roman: "ná", english: "softening particle", pos: "particle", category: "function words", art: {type:"text", gloss:"softener"} },
  { rank: 390, thai: "เลย", roman: "loei", english: "at all, indeed", pos: "adverb", category: "function words", art: {type:"text", gloss:"at all"} },
  { rank: 391, thai: "อีก", roman: "ìik", english: "again, more", pos: "adverb", category: "function words", art: {type:"text", gloss:"again / more"} },
  { rank: 392, thai: "หน่อย", roman: "nòi", english: "a little (in requests)", pos: "adverb", category: "function words", art: {type:"text", gloss:"a little"} },
  { rank: 393, thai: "นิด", roman: "nít", english: "a bit", pos: "adverb", category: "function words", art: {type:"text", gloss:"a bit"} },
  { rank: 394, thai: "เท่านั้น", roman: "thâonán", english: "only", pos: "adverb", category: "function words", art: {type:"text", gloss:"only"} },
  { rank: 395, thai: "ทั้ง", roman: "tháng", english: "all, both", pos: "determiner", category: "function words", art: {type:"text", gloss:"all / both"} },
  { rank: 396, thai: "แต่ละ", roman: "tàelá", english: "each", pos: "determiner", category: "function words", art: {type:"text", gloss:"each"} },
  { rank: 397, thai: "อัน", roman: "an", english: "classifier for things", pos: "noun", category: "function words", art: {type:"text", gloss:"clf: thing"} },
  { rank: 398, thai: "ตัว", roman: "tua", english: "body, classifier for animals", pos: "noun", category: "function words", art: {type:"text", gloss:"clf: animal"} },
  { rank: 399, thai: "ใบ", roman: "bai", english: "classifier for sheets", pos: "noun", category: "function words", art: {type:"text", gloss:"clf: sheet"} },
  { rank: 400, thai: "เล่ม", roman: "lêm", english: "classifier for books", pos: "noun", category: "function words", art: {type:"text", gloss:"clf: book"} },
  { rank: 401, thai: "คัน", roman: "khan", english: "classifier for vehicles", pos: "noun", category: "function words", art: {type:"text", gloss:"clf: vehicle"} },
  { rank: 402, thai: "ที่นี่", roman: "thîinîi", english: "here", pos: "adverb", category: "places", art: {type:"text", gloss:"here"} },
  { rank: 403, thai: "ที่นั่น", roman: "thîinân", english: "there", pos: "adverb", category: "places", art: {type:"text", gloss:"there"} },
  { rank: 404, thai: "นั้น", roman: "nán", english: "that", pos: "determiner", category: "function words", art: {type:"text", gloss:"that"} },
  { rank: 405, thai: "ไหน", roman: "nǎi", english: "which", pos: "question", category: "question words", art: {type:"text", gloss:"which?"} },
  { rank: 406, thai: "เท่าไหร่", roman: "thâorài", english: "how much", pos: "question", category: "question words", art: {type:"text", gloss:"how much?"} },
  { rank: 407, thai: "กี่", roman: "kìi", english: "how many", pos: "question", category: "question words", art: {type:"text", gloss:"how many?"} },
  { rank: 408, thai: "ทำงาน", roman: "thamngaan", english: "to work", pos: "verb", category: "verbs", art: {type:"glyph", icon:"tool", mod:"bars"} },
  { rank: 409, thai: "งาน", roman: "ngaan", english: "work, job, party", pos: "noun", category: "abstract", art: {type:"glyph", icon:"bag", mod:"tool"} },
  { rank: 410, thai: "เล่น", roman: "lên", english: "to play", pos: "verb", category: "verbs", art: {type:"glyph", icon:"star", mod:"smile"} },
  { rank: 411, thai: "ร้อง", roman: "róong", english: "to sing, to cry out", pos: "verb", category: "verbs", art: {type:"glyph", icon:"music", mod:"mouth"} },
  { rank: 412, thai: "หัวเราะ", roman: "hǔaró", english: "to laugh", pos: "verb", category: "verbs", art: {type:"glyph", icon:"smile", mod:"bolt"} },
  { rank: 413, thai: "ร้องไห้", roman: "róonghâi", english: "to cry", pos: "verb", category: "verbs", art: {type:"glyph", icon:"frown", mod:"drop"} },
  { rank: 414, thai: "ยิ้ม", roman: "yím", english: "to smile", pos: "verb", category: "verbs", art: {type:"glyph", icon:"smile"} },
  { rank: 415, thai: "จำ", roman: "cham", english: "to remember", pos: "verb", category: "verbs", art: {type:"glyph", icon:"brain", mod:"check"} },
  { rank: 416, thai: "ลืม", roman: "luem", english: "to forget", pos: "verb", category: "verbs", art: {type:"glyph", icon:"brain", mod:"cross"} },
  { rank: 417, thai: "เข้าใจ", roman: "khâochai", english: "to understand", pos: "verb", category: "verbs", art: {type:"glyph", icon:"brain", mod:"bolt"} },
  { rank: 418, thai: "สงสัย", roman: "sǒngsǎi", english: "to wonder, to doubt", pos: "verb", category: "verbs", art: {type:"glyph", icon:"brain", mod:"question"} },
  { rank: 419, thai: "เชื่อ", roman: "chûea", english: "to believe", pos: "verb", category: "verbs", art: {type:"glyph", icon:"brain", mod:"heart"} },
  { rank: 420, thai: "หวัง", roman: "wǎng", english: "to hope", pos: "verb", category: "verbs", art: {type:"glyph", icon:"star", mod:"heart"} },
  { rank: 421, thai: "ลอง", roman: "loong", english: "to try", pos: "verb", category: "verbs", art: {type:"glyph", icon:"target", mod:"question"} },
  { rank: 422, thai: "เริ่ม", roman: "rôem", english: "to begin", pos: "verb", category: "verbs", art: {type:"glyph", icon:"flag"} },
  { rank: 423, thai: "หยุด", roman: "yùt", english: "to stop", pos: "verb", category: "verbs", art: {type:"glyph", icon:"ban"} },
  { rank: 424, thai: "จบ", roman: "chòp", english: "to end", pos: "verb", category: "verbs", art: {type:"glyph", icon:"flag", mod:"check"} },
  { rank: 425, thai: "เปลี่ยน", roman: "plìan", english: "to change", pos: "verb", category: "verbs", art: {type:"glyph", icon:"arrows-swap"} },
  { rank: 426, thai: "เลือก", roman: "lûeak", english: "to choose", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"check"} },
  { rank: 427, thai: "ตัด", roman: "tàt", english: "to cut", pos: "verb", category: "verbs", art: {type:"glyph", icon:"scissors"} },
  { rank: 428, thai: "สร้าง", roman: "sâang", english: "to build", pos: "verb", category: "verbs", art: {type:"glyph", icon:"box", mod:"plus"} },
  { rank: 429, thai: "ซ่อม", roman: "sôom", english: "to repair", pos: "verb", category: "verbs", art: {type:"glyph", icon:"tool", mod:"check"} },
  { rank: 430, thai: "ล้าง", roman: "láang", english: "to wash", pos: "verb", category: "verbs", art: {type:"glyph", icon:"drop", mod:"spark"} },
  { rank: 431, thai: "อาบน้ำ", roman: "àapnáam", english: "to bathe", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person", mod:"drop"} },
  { rank: 432, thai: "แปรงฟัน", roman: "praengfan", english: "to brush one's teeth", pos: "verb", category: "verbs", art: {type:"glyph", icon:"smile", mod:"spark"} },
  { rank: 433, thai: "ใส่", roman: "sài", english: "to wear, to put in", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person", mod:"shield"} },
  { rank: 434, thai: "ถอด", roman: "thòot", english: "to take off", pos: "verb", category: "verbs", art: {type:"glyph", icon:"person", mod:"arrow-down"} },
  { rank: 435, thai: "ทำอาหาร", roman: "tham-aahǎan", english: "to cook", pos: "verb", category: "verbs", art: {type:"glyph", icon:"bowl", mod:"fire"} },
  { rank: 436, thai: "ชิม", roman: "chim", english: "to taste", pos: "verb", category: "verbs", art: {type:"glyph", icon:"mouth", mod:"star"} },
  { rank: 437, thai: "แตะ", roman: "tàe", english: "to touch", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"spark"} },
  { rank: 438, thai: "ผลัก", roman: "phlàk", english: "to push", pos: "verb", category: "verbs", art: {type:"glyph", icon:"box", mod:"arrow-right"} },
  { rank: 439, thai: "ดึง", roman: "dueng", english: "to pull", pos: "verb", category: "verbs", art: {type:"glyph", icon:"box", mod:"arrow-left"} },
  { rank: 440, thai: "โยน", roman: "yoon", english: "to throw", pos: "verb", category: "verbs", art: {type:"glyph", icon:"box", mod:"arrow-up"} },
  { rank: 441, thai: "จับ", roman: "chàp", english: "to catch, to grab", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"target"} },
  { rank: 442, thai: "เก็บ", roman: "kèp", english: "to keep, to collect", pos: "verb", category: "verbs", art: {type:"glyph", icon:"box", mod:"check"} },
  { rank: 443, thai: "ทิ้ง", roman: "thíng", english: "to throw away", pos: "verb", category: "verbs", art: {type:"glyph", icon:"trash"} },
  { rank: 444, thai: "เช่า", roman: "châo", english: "to rent", pos: "verb", category: "verbs", art: {type:"glyph", icon:"house", mod:"coin"} },
  { rank: 445, thai: "ยืม", roman: "yuem", english: "to borrow", pos: "verb", category: "verbs", art: {type:"glyph", icon:"hand", mod:"arrow-cycle"} },
  { rank: 446, thai: "ชนะ", roman: "chaná", english: "to win", pos: "verb", category: "verbs", art: {type:"glyph", icon:"medal"} },
  { rank: 447, thai: "แพ้", roman: "pháe", english: "to lose, to be allergic", pos: "verb", category: "verbs", art: {type:"glyph", icon:"medal", mod:"cross"} },
  { rank: 448, thai: "แข่ง", roman: "khàeng", english: "to compete", pos: "verb", category: "verbs", art: {type:"glyph", icon:"flag", mod:"person-run"} },
  { rank: 449, thai: "ฝึก", roman: "fùek", english: "to practise", pos: "verb", category: "verbs", art: {type:"glyph", icon:"arrow-cycle", mod:"target"} },
  { rank: 450, thai: "สอบ", roman: "sòop", english: "to sit an exam", pos: "verb", category: "verbs", art: {type:"glyph", icon:"note", mod:"pen"} },
  { rank: 451, thai: "ผ่าน", roman: "phàan", english: "to pass", pos: "verb", category: "verbs", art: {type:"glyph", icon:"check", mod:"arrow-right"} },
  { rank: 452, thai: "เตรียม", roman: "triam", english: "to prepare", pos: "verb", category: "verbs", art: {type:"glyph", icon:"box", mod:"bars"} },
  { rank: 453, thai: "วางแผน", roman: "waangphǎen", english: "to plan", pos: "verb", category: "verbs", art: {type:"glyph", icon:"grid", mod:"pen"} },
  { rank: 454, thai: "ตัดสินใจ", roman: "tàtsǐnchai", english: "to decide", pos: "verb", category: "verbs", art: {type:"glyph", icon:"scale", mod:"check"} },
  { rank: 455, thai: "เรื่อง", roman: "rûeang", english: "story, matter", pos: "noun", category: "abstract", art: {type:"glyph", icon:"book", mod:"speech"} },
  { rank: 456, thai: "ปัญหา", roman: "panhǎa", english: "problem", pos: "noun", category: "abstract", art: {type:"glyph", icon:"exclaim", mod:"box"} },
  { rank: 457, thai: "เหตุผล", roman: "hèetphǒn", english: "reason", pos: "noun", category: "abstract", art: {type:"glyph", icon:"link", mod:"brain"} },
  { rank: 458, thai: "ความคิด", roman: "khwaamkhít", english: "idea", pos: "noun", category: "abstract", art: {type:"glyph", icon:"bolt", mod:"brain"} },
  { rank: 459, thai: "ข่าว", roman: "khàao", english: "news", pos: "noun", category: "abstract", art: {type:"glyph", icon:"note", mod:"bell"} },
  { rank: 460, thai: "ข้อมูล", roman: "khôomuun", english: "information, data", pos: "noun", category: "abstract", art: {type:"glyph", icon:"grid", mod:"bars"} },
  { rank: 461, thai: "คำ", roman: "kham", english: "word", pos: "noun", category: "abstract", art: {type:"glyph", icon:"note"} },
  { rank: 462, thai: "ภาษา", roman: "phaasǎa", english: "language", pos: "noun", category: "abstract", art: {type:"glyph", icon:"speech", mod:"people"} },
  { rank: 463, thai: "เสียง", roman: "sǐang", english: "sound, voice", pos: "noun", category: "abstract", art: {type:"glyph", icon:"music"} },
  { rank: 464, thai: "ความจริง", roman: "khwaamching", english: "truth", pos: "noun", category: "abstract", art: {type:"glyph", icon:"check", mod:"shield"} },
  { rank: 465, thai: "โอกาส", roman: "ookàat", english: "opportunity", pos: "noun", category: "abstract", art: {type:"glyph", icon:"door", mod:"star"} },
  { rank: 466, thai: "ผล", roman: "phǒn", english: "result, fruit", pos: "noun", category: "abstract", art: {type:"glyph", icon:"target", mod:"check"} },
  { rank: 467, thai: "วิธี", roman: "wíthii", english: "method, way", pos: "noun", category: "abstract", art: {type:"glyph", icon:"link", mod:"arrow-right"} },
  { rank: 468, thai: "แบบ", roman: "bàep", english: "style, type", pos: "noun", category: "abstract", art: {type:"glyph", icon:"grid", mod:"star"} },
  { rank: 469, thai: "ส่วน", roman: "sùan", english: "part, portion", pos: "noun", category: "abstract", art: {type:"glyph", icon:"pie"} },
  { rank: 470, thai: "ระบบ", roman: "rabòp", english: "system", pos: "noun", category: "abstract", art: {type:"glyph", icon:"grid", mod:"link"} },
  { rank: 471, thai: "กฎ", roman: "kòt", english: "rule, law", pos: "noun", category: "abstract", art: {type:"glyph", icon:"book", mod:"shield"} },
  { rank: 472, thai: "หน้าที่", roman: "nâathîi", english: "duty", pos: "noun", category: "abstract", art: {type:"glyph", icon:"note", mod:"check"} },
  { rank: 473, thai: "ความสุข", roman: "khwaamsùk", english: "happiness", pos: "noun", category: "abstract", art: {type:"glyph", icon:"smile", mod:"sun"} },
  { rank: 474, thai: "ความฝัน", roman: "khwaamfǎn", english: "dream", pos: "noun", category: "abstract", art: {type:"glyph", icon:"cloud", mod:"moon"} },
  { rank: 475, thai: "ราคา", roman: "raakhaa", english: "price", pos: "noun", category: "abstract", art: {type:"glyph", icon:"coin", mod:"note"} },
  { rank: 476, thai: "จำนวน", roman: "chamnuan", english: "amount", pos: "noun", category: "abstract", art: {type:"glyph", icon:"bars", mod:"note"} },
  { rank: 477, thai: "ขนาด", roman: "khanàat", english: "size", pos: "noun", category: "abstract", art: {type:"glyph", icon:"ruler", mod:"box"} },
  { rank: 478, thai: "น้ำหนัก", roman: "námnàk", english: "weight", pos: "noun", category: "abstract", art: {type:"glyph", icon:"scale"} },
  { rank: 479, thai: "รัฐบาล", roman: "rátthabaan", english: "government", pos: "noun", category: "abstract", art: {type:"glyph", icon:"flag", mod:"shield"} },
  { rank: 480, thai: "บริษัท", roman: "boorisàt", english: "company", pos: "noun", category: "places", art: {type:"emoji", char:"🏢"} },
  { rank: 481, thai: "ห้องน้ำ", roman: "hôngnáam", english: "toilet, bathroom", pos: "noun", category: "places", art: {type:"emoji", char:"🚻"} },
  { rank: 482, thai: "ครัว", roman: "khrua", english: "kitchen", pos: "noun", category: "places", art: {type:"emoji", char:"🍳"} },
  { rank: 483, thai: "หมู่บ้าน", roman: "mùubâan", english: "village", pos: "noun", category: "places", art: {type:"emoji", char:"🏘️"} },
  { rank: 484, thai: "จังหวัด", roman: "changwàt", english: "province", pos: "noun", category: "places", art: {type:"emoji", char:"🗺️"} },
  { rank: 485, thai: "โลก", roman: "lôok", english: "world, earth", pos: "noun", category: "nature", art: {type:"emoji", char:"🌍"} },
  { rank: 486, thai: "ดวงอาทิตย์", roman: "duang-aathít", english: "sun", pos: "noun", category: "nature", art: {type:"emoji", char:"☀️"} },
  { rank: 487, thai: "ดวงจันทร์", roman: "duangchan", english: "moon", pos: "noun", category: "nature", art: {type:"emoji", char:"🌙"} },
  { rank: 488, thai: "ดาว", roman: "daao", english: "star", pos: "noun", category: "nature", art: {type:"emoji", char:"⭐"} },
  { rank: 489, thai: "เมฆ", roman: "mêek", english: "cloud", pos: "noun", category: "nature", art: {type:"emoji", char:"☁️"} },
  { rank: 490, thai: "หิน", roman: "hǐn", english: "stone", pos: "noun", category: "nature", art: {type:"emoji", char:"🪨"} },
  { rank: 491, thai: "ดิน", roman: "din", english: "soil", pos: "noun", category: "nature", art: {type:"glyph", icon:"grid", mod:"leaf"} },
  { rank: 492, thai: "ใบไม้", roman: "baimáai", english: "leaf", pos: "noun", category: "nature", art: {type:"emoji", char:"🍃"} },
  { rank: 493, thai: "ทอง", roman: "thoong", english: "gold", pos: "noun", category: "objects", art: {type:"emoji", char:"🥇"} },
  { rank: 494, thai: "แก้ว", roman: "kâeo", english: "glass, drinking glass", pos: "noun", category: "objects", art: {type:"emoji", char:"🥃"} },
  { rank: 495, thai: "จาน", roman: "chaan", english: "plate", pos: "noun", category: "objects", art: {type:"emoji", char:"🍽️"} },
  { rank: 496, thai: "ช้อน", roman: "chóon", english: "spoon", pos: "noun", category: "objects", art: {type:"emoji", char:"🥄"} },
  { rank: 497, thai: "มีด", roman: "mîit", english: "knife", pos: "noun", category: "objects", art: {type:"emoji", char:"🔪"} },
  { rank: 498, thai: "ยา", roman: "yaa", english: "medicine", pos: "noun", category: "objects", art: {type:"emoji", char:"💊"} },
  { rank: 499, thai: "ผ้า", roman: "phâa", english: "cloth", pos: "noun", category: "objects", art: {type:"emoji", char:"🧵"} },
  { rank: 500, thai: "ไม้", roman: "máai", english: "wood", pos: "noun", category: "objects", art: {type:"emoji", char:"🪵"} },
]

/* Category order is also the colour order used by the tiles. */
const CATEGORIES = ["function words", "verbs", "family & people", "pronouns", "adjectives", "places", "nature", "food & drink", "body", "question words", "numbers", "colors", "animals", "time & dates", "transport", "objects", "abstract"];

const UNIT_SIZE = 25;
const UNIT_COUNT = WORDS.length / UNIT_SIZE;
